/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as VerifyEmailRouteImport } from "./routes/verify-email"
import { Route as SignupRouteImport } from "./routes/signup"
import { Route as SigninRouteImport } from "./routes/signin"
import { Route as AuthenticatedRouteImport } from "./routes/_authenticated"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as PublicSlugRouteImport } from "./routes/public.$slug"
import { Route as AuthenticatedTimerRouteImport } from "./routes/_authenticated/timer"
import { Route as AuthenticatedTagsRouteImport } from "./routes/_authenticated/tags"
import { Route as AuthenticatedSettingsRouteImport } from "./routes/_authenticated/settings"
import { Route as AuthenticatedScheduleRouteImport } from "./routes/_authenticated/schedule"
import { Route as AuthenticatedPublicViewsRouteImport } from "./routes/_authenticated/public-views"
import { Route as AuthenticatedNetworkRouteImport } from "./routes/_authenticated/network"
import { Route as AuthenticatedMessagesRouteImport } from "./routes/_authenticated/messages"
import { Route as AuthenticatedIntegrationsRouteImport } from "./routes/_authenticated/integrations"
import { Route as AuthenticatedDashboardRouteImport } from "./routes/_authenticated/dashboard"
import { Route as AuthenticatedMessagesIndexRouteImport } from "./routes/_authenticated/messages/index"
import { Route as AuthenticatedMessagesThreadIdRouteImport } from "./routes/_authenticated/messages/$threadId"
import { Route as AuthenticatedInvitesInviteIdRouteImport } from "./routes/_authenticated/invites.$inviteId"

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: "/verify-email",
  path: "/verify-email",
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: "/signup",
  path: "/signup",
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: "/signin",
  path: "/signin",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const PublicSlugRoute = PublicSlugRouteImport.update({
  id: "/public/$slug",
  path: "/public/$slug",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTimerRoute = AuthenticatedTimerRouteImport.update({
  id: "/timer",
  path: "/timer",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTagsRoute = AuthenticatedTagsRouteImport.update({
  id: "/tags",
  path: "/tags",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: "/schedule",
  path: "/schedule",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPublicViewsRoute =
  AuthenticatedPublicViewsRouteImport.update({
    id: "/public-views",
    path: "/public-views",
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNetworkRoute = AuthenticatedNetworkRouteImport.update({
  id: "/network",
  path: "/network",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: "/messages",
  path: "/messages",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: "/integrations",
    path: "/integrations",
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMessagesIndexRoute =
  AuthenticatedMessagesIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthenticatedMessagesRoute,
  } as any)
const AuthenticatedMessagesThreadIdRoute =
  AuthenticatedMessagesThreadIdRouteImport.update({
    id: "/$threadId",
    path: "/$threadId",
    getParentRoute: () => AuthenticatedMessagesRoute,
  } as any)
const AuthenticatedInvitesInviteIdRoute =
  AuthenticatedInvitesInviteIdRouteImport.update({
    id: "/invites/$inviteId",
    path: "/invites/$inviteId",
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/signin": typeof SigninRoute
  "/signup": typeof SignupRoute
  "/verify-email": typeof VerifyEmailRoute
  "/dashboard": typeof AuthenticatedDashboardRoute
  "/integrations": typeof AuthenticatedIntegrationsRoute
  "/messages": typeof AuthenticatedMessagesRouteWithChildren
  "/network": typeof AuthenticatedNetworkRoute
  "/public-views": typeof AuthenticatedPublicViewsRoute
  "/schedule": typeof AuthenticatedScheduleRoute
  "/settings": typeof AuthenticatedSettingsRoute
  "/tags": typeof AuthenticatedTagsRoute
  "/timer": typeof AuthenticatedTimerRoute
  "/public/$slug": typeof PublicSlugRoute
  "/invites/$inviteId": typeof AuthenticatedInvitesInviteIdRoute
  "/messages/$threadId": typeof AuthenticatedMessagesThreadIdRoute
  "/messages/": typeof AuthenticatedMessagesIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/signin": typeof SigninRoute
  "/signup": typeof SignupRoute
  "/verify-email": typeof VerifyEmailRoute
  "/dashboard": typeof AuthenticatedDashboardRoute
  "/integrations": typeof AuthenticatedIntegrationsRoute
  "/network": typeof AuthenticatedNetworkRoute
  "/public-views": typeof AuthenticatedPublicViewsRoute
  "/schedule": typeof AuthenticatedScheduleRoute
  "/settings": typeof AuthenticatedSettingsRoute
  "/tags": typeof AuthenticatedTagsRoute
  "/timer": typeof AuthenticatedTimerRoute
  "/public/$slug": typeof PublicSlugRoute
  "/invites/$inviteId": typeof AuthenticatedInvitesInviteIdRoute
  "/messages/$threadId": typeof AuthenticatedMessagesThreadIdRoute
  "/messages": typeof AuthenticatedMessagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/_authenticated": typeof AuthenticatedRouteWithChildren
  "/signin": typeof SigninRoute
  "/signup": typeof SignupRoute
  "/verify-email": typeof VerifyEmailRoute
  "/_authenticated/dashboard": typeof AuthenticatedDashboardRoute
  "/_authenticated/integrations": typeof AuthenticatedIntegrationsRoute
  "/_authenticated/messages": typeof AuthenticatedMessagesRouteWithChildren
  "/_authenticated/network": typeof AuthenticatedNetworkRoute
  "/_authenticated/public-views": typeof AuthenticatedPublicViewsRoute
  "/_authenticated/schedule": typeof AuthenticatedScheduleRoute
  "/_authenticated/settings": typeof AuthenticatedSettingsRoute
  "/_authenticated/tags": typeof AuthenticatedTagsRoute
  "/_authenticated/timer": typeof AuthenticatedTimerRoute
  "/public/$slug": typeof PublicSlugRoute
  "/_authenticated/invites/$inviteId": typeof AuthenticatedInvitesInviteIdRoute
  "/_authenticated/messages/$threadId": typeof AuthenticatedMessagesThreadIdRoute
  "/_authenticated/messages/": typeof AuthenticatedMessagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/signin"
    | "/signup"
    | "/verify-email"
    | "/dashboard"
    | "/integrations"
    | "/messages"
    | "/network"
    | "/public-views"
    | "/schedule"
    | "/settings"
    | "/tags"
    | "/timer"
    | "/public/$slug"
    | "/invites/$inviteId"
    | "/messages/$threadId"
    | "/messages/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/signin"
    | "/signup"
    | "/verify-email"
    | "/dashboard"
    | "/integrations"
    | "/network"
    | "/public-views"
    | "/schedule"
    | "/settings"
    | "/tags"
    | "/timer"
    | "/public/$slug"
    | "/invites/$inviteId"
    | "/messages/$threadId"
    | "/messages"
  id:
    | "__root__"
    | "/"
    | "/_authenticated"
    | "/signin"
    | "/signup"
    | "/verify-email"
    | "/_authenticated/dashboard"
    | "/_authenticated/integrations"
    | "/_authenticated/messages"
    | "/_authenticated/network"
    | "/_authenticated/public-views"
    | "/_authenticated/schedule"
    | "/_authenticated/settings"
    | "/_authenticated/tags"
    | "/_authenticated/timer"
    | "/public/$slug"
    | "/_authenticated/invites/$inviteId"
    | "/_authenticated/messages/$threadId"
    | "/_authenticated/messages/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  PublicSlugRoute: typeof PublicSlugRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/verify-email": {
      id: "/verify-email"
      path: "/verify-email"
      fullPath: "/verify-email"
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/signup": {
      id: "/signup"
      path: "/signup"
      fullPath: "/signup"
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/signin": {
      id: "/signin"
      path: "/signin"
      fullPath: "/signin"
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authenticated": {
      id: "/_authenticated"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/public/$slug": {
      id: "/public/$slug"
      path: "/public/$slug"
      fullPath: "/public/$slug"
      preLoaderRoute: typeof PublicSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authenticated/timer": {
      id: "/_authenticated/timer"
      path: "/timer"
      fullPath: "/timer"
      preLoaderRoute: typeof AuthenticatedTimerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/tags": {
      id: "/_authenticated/tags"
      path: "/tags"
      fullPath: "/tags"
      preLoaderRoute: typeof AuthenticatedTagsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/settings": {
      id: "/_authenticated/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/schedule": {
      id: "/_authenticated/schedule"
      path: "/schedule"
      fullPath: "/schedule"
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/public-views": {
      id: "/_authenticated/public-views"
      path: "/public-views"
      fullPath: "/public-views"
      preLoaderRoute: typeof AuthenticatedPublicViewsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/network": {
      id: "/_authenticated/network"
      path: "/network"
      fullPath: "/network"
      preLoaderRoute: typeof AuthenticatedNetworkRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/messages": {
      id: "/_authenticated/messages"
      path: "/messages"
      fullPath: "/messages"
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/integrations": {
      id: "/_authenticated/integrations"
      path: "/integrations"
      fullPath: "/integrations"
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/dashboard": {
      id: "/_authenticated/dashboard"
      path: "/dashboard"
      fullPath: "/dashboard"
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/messages/": {
      id: "/_authenticated/messages/"
      path: "/"
      fullPath: "/messages/"
      preLoaderRoute: typeof AuthenticatedMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedMessagesRoute
    }
    "/_authenticated/messages/$threadId": {
      id: "/_authenticated/messages/$threadId"
      path: "/$threadId"
      fullPath: "/messages/$threadId"
      preLoaderRoute: typeof AuthenticatedMessagesThreadIdRouteImport
      parentRoute: typeof AuthenticatedMessagesRoute
    }
    "/_authenticated/invites/$inviteId": {
      id: "/_authenticated/invites/$inviteId"
      path: "/invites/$inviteId"
      fullPath: "/invites/$inviteId"
      preLoaderRoute: typeof AuthenticatedInvitesInviteIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedMessagesRouteChildren {
  AuthenticatedMessagesThreadIdRoute: typeof AuthenticatedMessagesThreadIdRoute
  AuthenticatedMessagesIndexRoute: typeof AuthenticatedMessagesIndexRoute
}

const AuthenticatedMessagesRouteChildren: AuthenticatedMessagesRouteChildren = {
  AuthenticatedMessagesThreadIdRoute: AuthenticatedMessagesThreadIdRoute,
  AuthenticatedMessagesIndexRoute: AuthenticatedMessagesIndexRoute,
}

const AuthenticatedMessagesRouteWithChildren =
  AuthenticatedMessagesRoute._addFileChildren(
    AuthenticatedMessagesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRouteWithChildren
  AuthenticatedNetworkRoute: typeof AuthenticatedNetworkRoute
  AuthenticatedPublicViewsRoute: typeof AuthenticatedPublicViewsRoute
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTagsRoute: typeof AuthenticatedTagsRoute
  AuthenticatedTimerRoute: typeof AuthenticatedTimerRoute
  AuthenticatedInvitesInviteIdRoute: typeof AuthenticatedInvitesInviteIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRouteWithChildren,
  AuthenticatedNetworkRoute: AuthenticatedNetworkRoute,
  AuthenticatedPublicViewsRoute: AuthenticatedPublicViewsRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTagsRoute: AuthenticatedTagsRoute,
  AuthenticatedTimerRoute: AuthenticatedTimerRoute,
  AuthenticatedInvitesInviteIdRoute: AuthenticatedInvitesInviteIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  PublicSlugRoute: PublicSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
